Feature/gizmos
papagiannakis/Elements pull request #46
Opened 2023-10-11 11:03 UTC by kamarianakis

Feature: Ability to tab through all visible elements in the scene and manipulate TRS via Unity-like gizmos

2023-10-11 17:59 UTC, aprotopsaltis reviewed
- translation gizmo delays to follow the mouse
- achieving rotation was difficult in some cases to grab the rings, also producing some jittery motion in the rings
- scaling seems to be working on predefined axes. If first rotated and then scaled the issue is visible

2023-10-12 05:27 UTC, aprotopsaltis requested changes
additionally the test does not open a window.

2023-10-18 14:51 UTC, kamarianakis commented
- The rotation has been debugged, 
- The test_gizmos is not supposed to open a window, it contains 5 tests that are in the testing tab, all passing 
- No translation issue on my mac
- Indeed the scale are currently designed to work in local space, i.e., we do not update the scale gizmo upon rotation of the original object, to allow easier manipulation in 2D (no need to change the camera to properly look for the "hidden" axis

2023-10-19 17:35 UTC, aprotopsaltis approved these changes

2023-10-19 17:37 UTC, merged